AWSTemplateFormatVersion: "2010-09-09"
Description: Init DB Lambda to create tables

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  RDSSecretArn:
    Type: String
  RDSClusterEndpoint:
    Type: String
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  LambdaCodeBucket:
    Type: String
  LambdaCodeKey:
    Type: String
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name

Resources:
  InitDBLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: InitDBLambda
      Runtime: nodejs18.x
      Handler: src/init-db/index.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      MemorySize: 256
      Timeout: 20
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds: !Ref SubnetIds
      Environment:
        Variables:
          RDS_SECRET_ARN: !Ref RDSSecretArn
          DB_NAME: EventManagerDB
          DB_HOST: !Ref RDSClusterEndpoint
      Role: !GetAtt InitDBRole.Arn

  InitDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: InitDBLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InitDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RDSSecretArn
              - Effect: Allow
                Action:
                  - rds-db:connect
                Resource: "*"

Outputs:
  InitDBLambdaName:
    Description: Nombre de la Lambda de inicialización de la DB
    Value: !Ref InitDBLambda
